### ISSUE TITLE
AMQP support for UWP

### ISSUE THREAD

**Issue by seank-com** [Azure-Samples/iot-hub-xamarin-remote-monitoring-device#1]
A [comment](https://github.com/Azure-Samples/iot-hub-xamarin-remote-monitoring-device/blob/master/Common/AzureIoTSuiteRemoteMonitoringHelper.cs#L321) in device connection code indicates that only HTTP is supported for UWP. Is this true or obsolete?

**Comment by olivierbloch** [comment]
Hi Sean
sorry for the late response.
AMQP is now supported.
I am closing this one
